### ISSUE TITLE
Får ikke skole data ind - om barnet er kommet eller gået.

### ISSUE THREAD

**Issue by sanded001** [scaarup/aula#224]
**Describe the bug or problem (In Danish is OK)**

**Please answer the following**
- Version of integration: 1.5.1
- Version of Home Assistant: 2025.5.1
- [X ] I have more than one child
- [X ] My children are attending different schools / institutions

det skal siges at jeg kun bruger det på mit ene barn - som er skole relateret.

**REQUIRED! Provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```
- Restart Home Assistant
- Capture all log lines (from the integration only), save it to a file and attach it to here.

Lidt log fejl ::

Logger: homeassistant.config_entries
Kilde: config_entries.py:749
Første forekomst: 12.25.37 (1 occurrence)
Senest logget: 12.25.37

Error setting up entry Aula for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 139, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 182, in async_setup_entry
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Config entry Aula (01JVC9Y3R34X9Z6A1DNKJC4XEG) for aula.binary_sensor has already been setup!

og endnu en.

Logger: homeassistant.components.sensor
Kilde: runner.py:154
integration: Sensor ([dokumentation](https://www.home-assistant.io/integrations/sensor), [problemer](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
Første forekomst: 12.25.47 (1 occurrence)
Senest logget: 12.25.47

Setup of sensor platform aula is taking over 10 seconds.

endnu en 

Logger: homeassistant.helpers.frame
Kilde: helpers/frame.py:380
Første forekomst: 12.26.37 (1 occurrence)
Senest logget: 12.26.37

Detected code that calls async_forward_entry_setups for integration aula with title: Aula and entry_id: 01JVC9Y3R34X9Z6A1DNKJC4XEG, during setup without awaiting async_forward_entry_setups, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue

og denne 

Logger: custom_components.aula.sensor
Kilde: helpers/update_coordinator.py:393
integration: Aula ([dokumentation](https://github.com/scaarup/aula/blob/main/README.md), [problemer](https://github.com/scaarup/aula/issues))
Første forekomst: 12.26.00 (2 occurrences)
Senest logget: 12.27.55

Error requesting sensor data: HTTPSConnectionPool(host='www.aula.dk', port=443): Max retries exceeded with url: /portal/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1028)')))

en til

Logger: homeassistant
Kilde: custom_components/aula/client.py:224
integration: Aula ([dokumentation](https://github.com/scaarup/aula/blob/main/README.md), [problemer](https://github.com/scaarup/aula/issues))
Første forekomst: 12.26.00 (2 occurrences)
Senest logget: 12.27.55

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/aula/sensor.py", line 77, in async_setup_entry
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aula/client.py", line 224, in update_data
    self.apiurl + "?method=profiles.getProfilesByLogin", verify=True
    ^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'apiurl'

Håber det giver lidt - ved ikke om jeg er den eneste med problemet? :)

Har haft slettet og addet aula igen med brugernavn og password - unilogin.

**Comment by scaarup** [comment]
Hej.

Din log indeholder:

Error requesting sensor data: HTTPSConnectionPool(host='www.aula.dk', port=443): Max retries exceeded with url: /portal/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired

Når jeg selv kigger, så ser certifikatet ud til at være gyldigt:

notBefore=Dec  6 08:56:02 2024 GMT
notAfter=Jan  7 08:56:01 2026 GMT

Så jeg kan ikke genskabe din fejl. Er du bag en firewall/proxy med noget TLS inspection?

**Comment by sanded001** [comment]
naa men nu du siger det, så er min nabu casa også 

Remote UI
Your instance is not connected to Home Assistant Cloud

Remote address: Not available

tror de har lidt udfordringer, så hvis dette er grunden, så afventer jeg til nabu casa har fået fingeren ud :)

**Comment by sanded001** [comment]
fejlen lå hos mig. tak for god integration. :)
