### ISSUE TITLE
Sensor Fjernet?

### ISSUE THREAD

**Issue by ETE-Design** [scaarup/aula#284]
Jeg har førhen haft en sensor hvor jeg kunne se “Status” på mit barn - Så som om hun var kommet / sov / gået

Denne funktion ser nu ud til at være forsvundet i HA - Er der mulighed for den kan tilføjes igen? Har prøvet at fjerne min bruger for så at oprette den igen men herefter en selve “entitet” helt forsvundet.

**Comment by annoia** [comment]
Aula har dræbt muligheden for at logge ind med unilogin, så hvis ud er logget ud kan du ikke logge ind igen. :( Se #257

**Comment by scaarup** [comment]
Mit password holdt også op med at virke. Jeg gik ind på aula.dk i min browser, resettede mit Unilogin password - hvorefter jeg fik at vide jeg ikke længere kunne logge ind med Unilogin (forbeholdt elever). Men jeg tog det nye password og satte ind i HA integrationen, restartede HA og den logger fint ind :)

(Køge kommune)

**Comment by runemoennike** [comment]
Jeg har også kun aulamessage sensoren nu. Jeg har prøvet

1. At resette password til unilogin og genoprette entry'en.
2. Fjerne og geninstallere Aula integration via HACS.
3. Genstarte HA.

Jeg var ellers så glad for at have en hurtig og let måde at tjekke ugeplanen på :)

Loggen indeholder følgene linjer fra Aula integration:
```

2026-01-11 11:10:47.305 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration aula which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2026-01-11 11:10:47.333 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration aula which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2026-01-11 11:11:15.829 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.hacs entity: switch.aula_pre_release
2026-01-11 19:55:59.878 INFO (MainThread) [homeassistant.setup] Setting up aula
2026-01-11 19:55:59.879 INFO (MainThread) [custom_components.aula] 
Aula integration, version: 0.1.51
https://github.com/scaarup/aula/issues
2026-01-11 19:56:00.020 INFO (MainThread) [homeassistant.components.sensor] Setting up aula.sensor
2026-01-11 19:56:00.047 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up aula.binary_sensor
2026-01-11 19:56:00.089 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.aula entity: binary_sensor.aula_aulamessage
2026-01-11 19:56:01.996 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data
  File "/config/custom_components/aula/sensor.py", line 62, in async_update_data
  File "/config/custom_components/aula/client.py", line 231, in update_data
  File "/config/custom_components/aula/client.py", line 129, in login
2026-01-11 19:56:02.117 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor: 'Client' object has no attribute 'apiurl'
  File "/config/custom_components/aula/sensor.py", line 77, in async_setup_entry
  File "/config/custom_components/aula/client.py", line 224, in update_data
2026-01-11 20:37:30.883 INFO (MainThread) [custom_components.aula] 
Aula integration, version: 0.1.51
https://github.com/scaarup/aula/issues
2026-01-11 20:37:30.884 INFO (MainThread) [homeassistant.components.sensor] Setting up aula.sensor
2026-01-11 20:37:30.913 DEBUG (SyncWorker_1) [custom_components.aula.client] is_logged_in? False
2026-01-11 20:37:30.913 DEBUG (SyncWorker_1) [custom_components.aula.client] Logging in
2026-01-11 20:37:30.918 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Aula for binary_sensor
ValueError: Config entry Aula (************) for aula.binary_sensor has already been setup!
2026-01-11 20:37:32.238 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data
  File "/config/custom_components/aula/sensor.py", line 62, in async_update_data
  File "/config/custom_components/aula/client.py", line 231, in update_data
  File "/config/custom_components/aula/client.py", line 129, in login
2026-01-11 20:37:32.243 DEBUG (MainThread) [custom_components.aula.sensor] Finished fetching sensor data in 1.331 seconds (success: False)
2026-01-11 20:37:32.248 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor: 'Client' object has no attribute 'apiurl'
  File "/config/custom_components/aula/sensor.py", line 77, in async_setup_entry
  File "/config/custom_components/aula/client.py", line 224, in update_data
2026-01-11 20:37:32.259 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setups for integration aula with title: Aula and entry_id: **********, during setup without awaiting async_forward_entry_setups, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue

```

**Comment by pmuhlig** [comment]
> Jeg har også kun aulamessage sensoren nu. Jeg har prøvet
> 
> 1. At resette password til unilogin og genoprette entry'en.
> 2. Fjerne og geninstallere Aula integration via HACS.
> 3. Genstarte HA.
> 
> Jeg var ellers så glad for at have en hurtig og let måde at tjekke ugeplanen på :)
> 
> Loggen indeholder følgene linjer fra Aula integration:
> 
> ```
> 
> 2026-01-11 11:10:47.305 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration aula which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2026-01-11 11:10:47.333 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration aula which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2026-01-11 11:11:15.829 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.hacs entity: switch.aula_pre_release
> 2026-01-11 19:55:59.878 INFO (MainThread) [homeassistant.setup] Setting up aula
> 2026-01-11 19:55:59.879 INFO (MainThread) [custom_components.aula] 
> Aula integration, version: 0.1.51
> https://github.com/scaarup/aula/issues
> 2026-01-11 19:56:00.020 INFO (MainThread) [homeassistant.components.sensor] Setting up aula.sensor
> 2026-01-11 19:56:00.047 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up aula.binary_sensor
> 2026-01-11 19:56:00.089 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.aula entity: binary_sensor.aula_aulamessage
> 2026-01-11 19:56:01.996 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data
>   File "/config/custom_components/aula/sensor.py", line 62, in async_update_data
>   File "/config/custom_components/aula/client.py", line 231, in update_data
>   File "/config/custom_components/aula/client.py", line 129, in login
> 2026-01-11 19:56:02.117 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor: 'Client' object has no attribute 'apiurl'
>   File "/config/custom_components/aula/sensor.py", line 77, in async_setup_entry
>   File "/config/custom_components/aula/client.py", line 224, in update_data
> 2026-01-11 20:37:30.883 INFO (MainThread) [custom_components.aula] 
> Aula integration, version: 0.1.51
> https://github.com/scaarup/aula/issues
> 2026-01-11 20:37:30.884 INFO (MainThread) [homeassistant.components.sensor] Setting up aula.sensor
> 2026-01-11 20:37:30.913 DEBUG (SyncWorker_1) [custom_components.aula.client] is_logged_in? False
> 2026-01-11 20:37:30.913 DEBUG (SyncWorker_1) [custom_components.aula.client] Logging in
> 2026-01-11 20:37:30.918 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Aula for binary_sensor
> ValueError: Config entry Aula (************) for aula.binary_sensor has already been setup!
> 2026-01-11 20:37:32.238 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data
>   File "/config/custom_components/aula/sensor.py", line 62, in async_update_data
>   File "/config/custom_components/aula/client.py", line 231, in update_data
>   File "/config/custom_components/aula/client.py", line 129, in login
> 2026-01-11 20:37:32.243 DEBUG (MainThread) [custom_components.aula.sensor] Finished fetching sensor data in 1.331 seconds (success: False)
> 2026-01-11 20:37:32.248 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor: 'Client' object has no attribute 'apiurl'
>   File "/config/custom_components/aula/sensor.py", line 77, in async_setup_entry
>   File "/config/custom_components/aula/client.py", line 224, in update_data
> 2026-01-11 20:37:32.259 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setups for integration aula with title: Aula and entry_id: **********, during setup without awaiting async_forward_entry_setups, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue
> ```

Var også mega glad for denne. Håber på en løsning.

**Comment by scaarup** [comment]
I må gerne teste den nye version

**Comment by RKOvlesen** [comment]
Virker efter version Version 0.1.52 med direkte MitID login.

**Comment by pmuhlig** [comment]
> Virker efter version Version 0.1.52 med direkte MitID login.

Installerede du på ny? Eller kan man vare opdatere?

**Comment by scaarup** [comment]
Nogen af jer, der har det til at virke: har I én eller multiple MitID identiteter I skal vælge imellem ved auth?

**Comment by annoia** [comment]
> Nogen af jer, der har det til at virke: har I én eller multiple MitID identiteter I skal vælge imellem ved auth?

Jeg angiver mit login, og bliver sendt direkte til at skulle godkende i appen.

**Comment by JanHG** [comment]
Jeg får også Authentication error: Authentication failed: 'name'
Jeg har flere identiteter under samme MitID (privat og erhverv), men får ikke lov til at vælge imellem dem.

**Comment by pmuhlig** [comment]
> Jeg får også Authentication error: Authentication failed: 'name' Jeg har flere identiteter under samme MitID (privat og erhverv), men får ikke lov til at vælge imellem dem.

Jeg har også en privat og erhverv.

**Comment by JanHG** [comment]
> Har man samme brugernavn til alle identiteter?

Ja
